### ISSUE TITLE
Crashes dedicated server (Minecraft Forge 47.3.5)

### ISSUE THREAD

**Issue by TommyC81** [KLjiana/Hook#1]
On Minecraft Forge 47.3.5.

After shooting the hook, shortly after the hook starts pulling, the dedicated server crashes.

Full crash log:
[crash-2024-08-05_22.34.04-server.txt](https://github.com/user-attachments/files/16501586/crash-2024-08-05_22.34.04-server.txt)

Extract:
_-- Head --
Thread: Server thread
Suspected Mod: 
	Hook (hook), Version: 0.2
		at TRANSFORMER/hook@0.2/org.hook.mod.entity.hook.AbstractHookEntity.m_8119_(AbstractHookEntity.java:94)_

**Comment by KLjiana** [comment]
it is my problem, but I fix it now.
